src/BlogPeliculas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

src/blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('proximos-estrenos/', views.proximos_estrenos, name='proximos-estrenos'),
    path('resena-update/<int:pk>/', views.resena_update, name='resena_update'),
    path('resena-delete/<int:pk>/', views.resena_delete, name='resena_delete'),
    path('login/', views.MiLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='blog/logout.html'), name='logout'),
    path('buscar/', views.buscar, name='buscar')
]

src/blog/models.py
from django.db import models


class Genero(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.nombre


class Pelicula(models.Model):
    titulo = models.CharField(max_length=200)
    sinopsis = models.TextField()
    director = models.CharField(max_length=100)
    fecha_estreno = models.IntegerField()
    genero = models.ForeignKey(Genero, on_delete=models.PROTECT)

    def __str__(self):
        return self.titulo
    

class Resena(models.Model):
    pelicula = models.ForeignKey(Pelicula, on_delete=models.PROTECT)
    autor = models.CharField(max_length=100, null=True, blank = True)
    puntuacion = models.IntegerField()
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Reseña de {self.pelicula.titulo} por {self.autor}"

src/blog/forms.py
from django import forms
from .models import Resena
from django.contrib.auth.forms import AuthenticationForm

class ResenaForm(forms.ModelForm):
    class Meta:
        model = Resena
        fields = ['puntuacion', 'autor', 'comentario']
        widgets = {
            'puntuacion': forms.NumberInput(attrs={'min': 1, 'max': 10}),
            'autor': forms.TextInput(attrs={'placeholder': 'Nombre del autor'}),
            'comentario': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Escribe tu reseña aqui...'})
        }

class LoginForm(AuthenticationForm):
    class Meta:
        model = AuthenticationForm
        fields = ['username', 'password']

src/blog/views.py
from django.shortcuts import render, redirect
from .models import Genero, Pelicula, Resena
from . import models, forms
from django.contrib.auth.views import LoginView
from .forms import LoginForm
from django.urls import reverse_lazy

def index(request):
    generos = Genero.objects.all()
    peliculas = Pelicula.objects.all()
    resenas = Resena.objects.all()  

    if request.method == 'POST':
        form = forms.ResenaForm(request.POST)
        if form.is_valid():
            nueva_resena = form.save(commit=False)
            pelicula_id = request.POST.get('pelicula_id')
            try:
                nueva_resena.pelicula = models.Pelicula.objects.get(id=pelicula_id)
                nueva_resena.save()
                return redirect('blog:index')
            except models.Pelicula.DoesNotExist:
                return render(request, 'blog/index.html', {  
                'generos': generos,  
                'peliculas': peliculas,  
                'resenas': resenas, 
                'form': form,
                'error': "La película seleccionada no existe en la página aun."
    })
    else:
        form = forms.ResenaForm()



    return render(request, 'blog/index.html', {  
        'generos': generos,  
        'peliculas': peliculas,  
        'resenas': resenas, 
        'form': form
    })

def proximos_estrenos(request):
    return render(request, 'blog/proximos-estrenos.html')

def resena_update(request, pk):
    query = models.Resena.objects.get(id=pk)
    if request.method == "GET":
        form = forms.ResenaForm(instance=query)
    if request.method == "POST":
        form = forms.ResenaForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect('blog:index')
    return render(request, 'blog/resena_update.html', {'form': form})

def resena_delete(request, pk):
    query = models.Resena.objects.get(id=pk)
    if request.method == "POST":
        query.delete()
        return redirect('blog:index')
    return render(request, 'blog/resena_delete.html', {'query': query})

class MiLoginView(LoginView):
    template_name = 'blog/login.html'
    authentication_form = LoginForm
    next_page = reverse_lazy('blog:index')

def buscar(request):
    busqueda = request.GET.get('busqueda')

    if busqueda:
        peliculas = Pelicula.objects.filter(titulo__icontains=busqueda)
    else:
        peliculas = Pelicula.objects.all()
    
    return render(request, 'blog/buscar.html', {'peliculas': peliculas})

src/blog/templates/blog/base.html
{% include 'componentes/nav.html' %}

{% block content %} 
{% endblock content %}

{% include 'componentes/footer.html' %}

src/blog/templates/blog/buscar.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Resultados de la búsqueda para "{{ query }}"</h1>
    
    {% if peliculas %}
        <ul>
            {% for pelicula in peliculas %}
                <li>
                    <h3>{{ pelicula.titulo }}</h3>
                    <p>Género: {{ pelicula.genero.nombre }}</p>
                    <p>Descripción: {{ pelicula.sinopsis }}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No se encontraron películas que coincidan con tu búsqueda.</p>
    {% endif %}
{% endblock content %}

src/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% load static %}


<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog de Peliculas</title>
</head>
<body>
    
    
    {% block content %}
    <h1>Blog de Peliculas - Mirabel</h1>
    <img src="{% static 'blog/peliculas.webp' %}" alt="Peliculas" height = 70% width=100%>
    {% if user.is_authenticated %}
        <p>Bienvenido a nuestro blog de películas, donde podrás encontrar información sobre las mejores peliculas de la historia moderna.</p>
    {% else %}
        <p>Bienvenido a nuestro blog de películas, donde podrás encontrar información sobre las mejores peliculas de la historia moderna.</p>
        <p>Para ver próximos estrenos, inicia sesión.</p>
    {% endif %}
    <br>
    <h2>Peliculas</h2>
    <br>

    {% for pelicula in peliculas %}
        <h3>{{ pelicula.titulo }}</h3>
        <h4>Género: {{ pelicula.genero.nombre }}</h4>


        {% for resena in resenas %}
            {% if resena.pelicula.id == pelicula.id %} 
                <p><h4>Calificación: {{ resena.puntuacion }}</h4></p>
                <p><h4>Reseña:</h4> {{ resena.comentario }}
                    <h6>Autor: {{ resena.autor }}</h6>
                </p> 

                <form method="get" action="{% url 'blog:resena_update' pk=resena.id %}">
                    <button type="submit">Editar reseña</button>
                </form>
                <form method="get" action="{% url 'blog:resena_delete' pk=resena.id %}">
                    <button type="submit">Eliminar reseña</button>
                </form>
                <br>
                <br>
            {% endif %}
        {% endfor %}

        <form method="post" style="background-color: rgb(186, 185, 185); padding: 15px; ">
            {% csrf_token %}
            <input type="hidden" name="pelicula_id" value="{{ pelicula.id }}">
            {{ form.as_p }}
            <button type="submit">Enviar reseña</button>
            <br>
            <br>
        </form>
    <br>
    {% endfor %}
        
    {% endblock content %}

</body>
</html>

    
    

src/blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Iniciar sesión</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar sesión</button>
    </form>
    <p>
        ¿No tienes una cuenta?
    </p>
{% endblock content %}

src/blog/templates/blog/logout.html
{% extends 'blog/base.html' %}

{% block content %}
    <p>Has cerrado sesión correctamente</p>
    <a href="{% url 'blog:index' %}"><button>Volver</button></a>
{% endblock content %}

src/blog/templates/blog/proximos-estrenos.html
{% extends 'blog/base.html' %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proximos Estrenos</title>
</head>
<body>
    {% block content %}
        <h1>Próximos estrenos esperados</h1>
        <ul>
            <li>Misión Imposible: Sentencia final</li>
            <li>Lilo & Stitch</li>
            <li>Cómo entrenar a tu dragón</li>
            <li>Karate Kid: Leyendas</li>
            <li>Superman Legacy</li>
        </ul>
    {% endblock content %}

</body>
</html>

src/blog/templates/blog/resena_delete.html
{% extends 'blog/base.html' %}

{% block content %}
  <h1>Eliminar Reseña</h1>
  <p>¿Estás seguro de que deseas eliminar esta reseña?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Si, estoy seguro.</button>
  </form>
  <a href="{% url 'blog:index' %}"><button>Volver</button></a>
{% endblock content %}

src/blog/templates/blog/resena_update.html
{% extends 'blog/base.html' %}

{% block content %}
  <h1>Editar Reseña</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar cambios</button>
  </form>
{% endblock content %}

src/blog/templates/componentes/footer.html
<footer>Todos los derechos reservados.</footer>

src/blog/templates/componentes/nav.html
<nav>
    <ul>
        <li><a href="{% url 'blog:index' %}">Inicio</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'blog:proximos-estrenos' %}">Próximos estrenos - 2025</a></li>
            <form action="{% url 'blog:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Cerrar sesión</button>
            </form>
        {% else %}
            <li><a href="{% url 'blog:login' %}">Iniciar sesión</a></li>
        {% endif %}
        <form method="get" action="{% url 'blog:buscar' %}">
            <input type="text" name="busqueda" placeholder="Buscar peli..." required>
            <button type="submit">Buscar</button>
        </form>
    </ul>
</nav>